### ISSUE TITLE
Undefined variables and data pre-processing

### ISSUE THREAD

**Issue by TiankaiHang** [Johswald/learning_where_to_learn#1]
Hi,

Thanks for your nice work!!

I have several questions.
- Some variables are not defined before being used, e.g., `class_augmentations` in https://github.com/Johswald/learning_where_to_learn/blob/1441fec556a570a6bd688e0581352c830dba6f88/utils/utils.py#L120
- How do U pre-process the data for each task? In other words, how do U get the data for each task in detail? Where could we find the related code?

Best.

**Comment by Johswald** [comment]
Hi! Sorry about this part of the code! Since I never trained our setup on Omniglot, I did not pay attention to this. Probably you will become problems when using the model as is as well, you might have to change the network configs a bit. I think the default for class augmentations ist [Rotation([90, 180, 270])], see here https://github.com/tristandeleu/pytorch-meta/blob/d55d89ebd47f340180267106bde3e4b723f23762/torchmeta/datasets/helpers.py#L79

Here a link to a description of the default augmentations used in most papers, to the best of my knowledge. Hope that helps... 

https://tristandeleu.github.io/pytorch-meta/api_reference/datasets/
